### ISSUE TITLE
Bug - deleting task on Plantation inventory leads to strange behaviour

### ISSUE THREAD

**Issue by LeScruf** [mstenta/farm_nfa#109]
![image](https://user-images.githubusercontent.com/14791005/136026446-4f6311c1-88c7-4f9b-b2a2-f4a9c608d580.png)

resulted in this:

![image](https://user-images.githubusercontent.com/14791005/136026222-f31824cc-bec1-451b-94fd-373a30795023.png)

But the task was deleted.

**Comment by pcambra** [comment]
This should be fixed now :)

**Comment by pcambra** [comment]
@LeScruf this is strange, this is how it should behave instead

https://user-images.githubusercontent.com/104912/136243988-a48f4d5a-a120-4292-ba3e-4b4c9d905a90.mov

:

**Comment by LeScruf** [comment]
It happened just now twice in a row - I recorded the second time:

https://user-images.githubusercontent.com/14791005/136249787-143873bb-0af9-4c9a-a72d-cfbdf38b846a.mov
