### ISSUE TITLE
Branding - NFA

### ISSUE THREAD

**Issue by LeScruf** [mstenta/farm_nfa#123]
A quick one - we need to remove the top left FarmOS badge and replace it with an NFA logo:[](url
![NFA - Short Logo - better](https://user-images.githubusercontent.com/14791005/137457574-d4b10b79-ae8e-40c3-83ba-b0e408453dc0.png)
)

I think it's ok to cleave off the tree and just keep the 'NFA'
![NFA - Short Logo Acronym](https://user-images.githubusercontent.com/14791005/137457919-8aca1234-8df2-4471-854a-b8ca99e686f1.png)

**Comment by pcambra** [comment]
https://tenor.com/es/ver/make-it-bigger-rick-clash-royale-bigger-and-better-improve-it-gif-22754642

**Comment by LeScruf** [comment]
Here's the logo on very similar dimensions - width identical, height <2px
![NFA - Short Logo Acronym](https://user-images.githubusercontent.com/14791005/137858337-a2ee8c7d-0771-43c6-b9c9-0f9aac567e71.png)
.

**Comment by pcambra** [comment]
@LeScruf changed
