### ISSUE TITLE
Add migration for tree species from 1.x

### ISSUE THREAD

**Issue by pcambra** [mstenta/farm_nfa#126]
Related to #92

**Comment by pcambra** [comment]
@LeScruf could you please confirm?

**Comment by pcambra** [comment]
here we go, https://forests.nfa.go.ug/admin/structure/taxonomy/manage/tree_species/overview thanks @mstenta

**Comment by LeScruf** [comment]
Yes, looking good! Apologies for delayed reply - been off the net.
