### ISSUE TITLE
Rename "Groups" to "Projects"

### ISSUE THREAD

**Issue by mstenta** [mstenta/farm_nfa#13]
> A. Plantings
> 4.Group membership should be renamed as 'Project', with crops searchable / listable by Project

Maybe this is just a matter of changing the labels? I'm curious to understand how this will be used.

**Comment by LeScruf** [comment]
See https://github.com/mstenta/farm_nfa/issues/14

**Comment by mstenta** [comment]
I'm going to close this in favor of #14 - we have some ideas that we can discuss over there...
