### ISSUE TITLE
Bug - cannot delete logs

### ISSUE THREAD

**Issue by LeScruf** [mstenta/farm_nfa#139]
On the dashboard - when deleting logs, a 'client error' message is triggered and the logs are not deleted.

**Comment by pcambra** [comment]
@LeScruf I've just tested this and seems to be working, could you please give me more details?

**Comment by LeScruf** [comment]
Still not working my end - I restarted the browser as well as refreshed the cache - same error:
https://www.google.com/maps/d/edit?mid=1wb9dEytDHpWawMns5GX3t9K4M9cJwTY4&usp=sharing

**Comment by pcambra** [comment]
@LeScruf I still need more information, url you're doing this, what log you're doing this in, what you're pressing exactly? maybe a video?

**Comment by pcambra** [comment]
AH, this is on the dashboard itself, I didn't even know you could do this :)

**Comment by pcambra** [comment]
This is an upstream bug: https://www.drupal.org/project/farm/issues/3248657

**Comment by LeScruf** [comment]
Ah ok - patience Watson!

**Comment by pcambra** [comment]
@LeScruf this should be fixed now

**Comment by LeScruf** [comment]
Fixed it is! :)
