### ISSUE TITLE
Clarify what are the final asset types

### ISSUE THREAD

**Issue by pcambra** [mstenta/farm_nfa#59]

**Comment by mstenta** [comment]
Some notes from our call this morning:

- Forest assets vs Land assets
- Natural forests vs Plantations
- New asset types?
    - Compartment?
    - Crop? (to represent the crop that will be harvested) or perhaps Forest represents that, and we make a new CFR type?

Need a list of fields from Andrew to determine which asset types we need.

Also remember to think about asset fields and plan fields separately.

**Comment by mstenta** [comment]
> Crop? (to represent the crop that will be harvested) or perhaps Forest represents that, and we make a new CFR type?

Worth asking: does this NEED to be tracked in farmOS (it certainly can), or is it already being tracked in the Tree Farmer CRM, and will that suffice (with a simple link back to the higher level Forest/CFR/Land assets)?

**Comment by mstenta** [comment]
Notes June 4, 2021:

- Single Forest asset type
- Multi-select "Forest Type" w/ options: Natural stand, Plantation (checkboxes)
- Depending on which types are selected, show/hide relevant fields

Important to distinguish "hierarchy" considerations from "data model" considerations. Technically, there is no enforcement of asset hierarchy rules - this will ultimately be up to the users to follow their own rules - meaning eg: "CFRs should always be UNDER Estates", etc. Data model refers to what *fields* are available on each type.

Asset types:

- Land - Maybe Land is just an asset used for simple demarcations? No additional fields on them at all. Can be used for Ranges, Sectors, Blocks*, Nursery Bed
- CFR - These represent a legally protected area. They have a set of CFR-specific fields on them.
- Zone - These represent use-restriction areas (production - forest harvesting permitted, buffer zone - limited non-consumptive use, forest nature reserve - no use allowed)
- Compartment - These are within CFRs, and have a limited set of fields on them (eg: who set it up, year established, etc). Compartments host stands, which are planted, harvested, replanted, etc. There may be multiple stands in a compartment, sequentially as well as at the same time.
- Forest Stand - This represents the biomass. It will be harvested/archived/etc. It is located inside compartments. This is where we distinguish the natural vs plantation. This is the Forest asset type.

"When you have a forest area management plan, you can allocate that prescription to any of the above assets (CFR, Zone, Compartment, Forest Stand)"
    - Asset reference field(s)
        - One field that can reference ANY asset type, OR:
        - Three separate fields that reference specific asset types:
            - CFR reference field
            - Zone reference field
            - Compartment reference field
            - Forest Stand reference field

We will decide on "Blocks" later - Andrew needs to confer with colleagues about how those are managed, and how they relate to Compartments / Forest Stands.

CFRs have one or more Zones. Zones have one or more Compartments. In theory, CFRs should always have zones, but they don't currently. So perhaps we can create a single "placeholder" Zone for each CFR.

Zones have polygons. Those polygons are multiples of compartments.

Future access control considerations: Sector manager of a particular sector should have access to only the children of that sector (CFRs, Compartments, Blocks, etc). Add an "Owner" field to land assets? And limit their access to child assets.

Next steps:
    - Define the fields on each asset type
    - Think about what will be covered by Logs/Plans

**Comment by LeScruf** [comment]
Asse form field design at https://docs.google.com/spreadsheets/d/13SAtfA-iCbzW9dfbMd-HvYuY8LYmJ8BdS51D-dHO5ek/edit#gid=118171807

**Comment by mstenta** [comment]
Summary of asset types in document (and highlights of field changes):

- Land (Admin)
    - Use existing Land type, rename to "Land (Admin)"
    - Add custom land type configs
    - Add field: "If other, specify" (text)
    - Add field: "Person in-charge (i/c)" - add as bundle field so filter auto-appears
        - Also add field to Users: "Contact phone number"
        - When the person in charge is selected, pull the phone number into the Land entity view page (via View Mode)
    - (KML will be there in farmOS alpha3)
- CFR (new asset type)
    - See doc.
    - Add custom entity type for "Boundary" - use inline entity form
    - ...
- Zone (new asset type)
     - See doc.
     - Also see fields under "Zonation" section of CFR in doc.
- Compartments
    - See doc.
- Blocks
    - See doc.
- Forest Stand
    - See doc.

**Comment by pcambra** [comment]
@mstenta as we change the whole asset structure, I  think we need to redo the migrations, or at least clear the data on the live instance, do you have any feedback about this?

**Comment by mstenta** [comment]
@pcambra Yes we will need to update the migrations once the asset types are settled. It should be easy, though. The current migrations are essentially just pulling in the "Areas" from the old system, and creating them as either Land or Forest assets depending on the "Area type" field from 1.x.

https://github.com/mstenta/farm_nfa/blob/2.x/web/modules/custom/farm_nfa/config/optional/migrate_plus.migration.farm_migrate_area_nfa_land.yml

https://github.com/mstenta/farm_nfa/blob/2.x/web/modules/custom/farm_nfa/config/optional/migrate_plus.migration.farm_migrate_area_nfa_forest.yml

So I think we can just create a new set of migration configs to map the existing area types to the new asset types, once we have those all in place.

**Comment by pcambra** [comment]
Thanks @mstenta :) could we for example rollback all existing migrations and rework them later?

**Comment by mstenta** [comment]
Sure that makes sense - it just means there will be no content (other than manually created) until the new asset types and migrations are ready - but that's probably OK.

**Comment by pcambra** [comment]
@LeScruf I've just deployed the asset type structure discussed here so you can evaluate what can be improved
