### ISSUE TITLE
Change "forest type" field on forest asset to be checkboxes

### ISSUE THREAD

**Issue by pcambra** [mstenta/farm_nfa#62]
This way a forest (CFR) can be Natural stand, plantation or both

Confirm with @mstenta if we make this change upstream in farm_forest

**Comment by pcambra** [comment]
@mstenta I think we can close this one, right?

**Comment by mstenta** [comment]
Yes! I did this on Monday after our call.

Here is the upstream issue for reference: https://www.drupal.org/project/farm_forest/issues/3219891
