### ISSUE TITLE
Mapbox underlay maps not displaying 

### ISSUE THREAD

**Issue by LeScruf** [mstenta/farm_nfa#63]
Just incase this hasn't been logged...

**Comment by mstenta** [comment]
@pcambra there are two pieces to this: 1) MapBox API key in `settings.local.php` (I think we set this up together), 2) Install the `farm_map_mapbox` module (maybe we can make this part of the exported config for future deployments).

For now I think `drush en farm_map_mapbox` will enable the MapBox layers...

**Comment by mstenta** [comment]
@LeScruf : @pcambra and I debugged this and realized it was due to the fact that the URL changed from nfa2x.farmos.net. The MapBox API key is associated with a specific set of URLs, so I added the new URL and now it should be working.
