### ISSUE TITLE
Clarify what are the final plan types

### ISSUE THREAD

**Issue by pcambra** [mstenta/farm_nfa#64]
See #59 

Reference: https://docs.google.com/spreadsheets/d/13SAtfA-iCbzW9dfbMd-HvYuY8LYmJ8BdS51D-dHO5ek/edit#gid=60580736

**Comment by mstenta** [comment]
It sounds like we should create a custom plan type called "Plantation plan", and move all the existing workflows/logic into that.

A prerequisite for this is to DISABLE the default "Forest" plan. Create a `farm_forest_plan` sub-module in the `farm_forest` project - move general plan to this, and do not enable in NFA.

In the future, we can add an additional plan type for "Natural forest plans" specifically for NFA.

**Comment by mstenta** [comment]
See "NFA asset, log, plan form fields" doc for Forest Plantation Plan fields.

**Comment by mstenta** [comment]
We talked about how it would be very nice to have a *single* form for creating:

- Forest plantation plan (plan)
- Forest asset (asset, forest type: plantation)
- Planting date (log)
- Planned harvest (log)
- Planned prescription (log)

**Comment by mstenta** [comment]
- Sketch out two plan types
    - Plantation Plan
    - Natural Forest Plan
- Disable the default Forest plan

**Comment by mstenta** [comment]
The custom plan types should reference CFR assets, not Forest assets, per discussion with @LeScruf today. We will need the ability to drill down to select the compartment/forest assets that logs are being applied to within the management, inventory, and harvest forms - which present children of the CFR(s) as available options.

**Comment by mstenta** [comment]
I pushed a commit that adds two custom plan types with a CFR reference field on each.
