### ISSUE TITLE
When you open a plantation plan, the "Inventory" tab should open the Plantation inventory log type form

### ISSUE THREAD

**Issue by pcambra** [mstenta/farm_nfa#70]
Create the plantation inventory bundle
Switch the form to use that for plantation plans

Working circle field should be hidden and a default value of "Production" should be saved for all plantation inventory logs.

**Comment by pcambra** [comment]
@LeScruf this is now deployed and the compartment autocomplete should display only compartments within the CFRs of the plan.

Can be tested in http://nfa.ddev.site/plans/plantation

**Comment by LeScruf** [comment]
Yes - seems to be working fine. Thks!
