### ISSUE TITLE
On plans filter, CFR need to be an autocomplete

### ISSUE THREAD

**Issue by pcambra** [mstenta/farm_nfa#75]
Also add type as a filter (Natural forest vs Plantation)

**Comment by pcambra** [comment]
@mstenta We already have the Parents field, maybe we should remove the field altogether

**Comment by pcambra** [comment]
I've removed the field for the time being

**Comment by pcambra** [comment]
We're limited by https://www.drupal.org/project/drupal/issues/2429699

**Comment by mstenta** [comment]
We are looking into either including the core patch from https://www.drupal.org/project/drupal/issues/2429699 in farmOS itself, or implementing our own plugin in the meantime. So assuming we get that working, this CFR field *should* become an autocomplete with the next release of farmOS.

> Also add type as a filter (Natural forest vs Plantation)

We have separate plan types for "Natural forest" and "Plantation" now so I don't think this is relevant anymore.

**Comment by mstenta** [comment]
> So assuming we get that working, this CFR field _should_ become an autocomplete with the next release of farmOS.

- #94 

I will close this issue if/when the solution is merged upstream, and then we can roll it out with #94.

**Comment by mstenta** [comment]
This did not make it into farmOS 2.0.0-alpha3, unfortunately - but should be finished soon. So we can either wait for a new tagged version that includes it or maybe pin to a commit hash if we need to. Or even include a patch if we want to stick with a tagged version. I'll update this again when we have it working upstream.

**Comment by paul121** [comment]
https://www.drupal.org/project/farm/issues/3185188#comment-14234000

I described two approaches in this comment. We are leaning towards using the core patch right now

**Comment by mstenta** [comment]
This is merged into farmOS 2.x :-)

Ready to deploy and test.
