### ISSUE TITLE
Add instructions on the CFRs field to indicate what to do to fix/add CFRs or add compartments

### ISSUE THREAD

**Issue by pcambra** [mstenta/farm_nfa#76]

**Comment by mstenta** [comment]
@pcambra can you post a quick screenshot of what this field looks like now? I can draft some copy for this.

**Comment by pcambra** [comment]
@mstenta as far as I understand this, this is for the add plan form, when you're adding a plantation/natural forest plan, there's a CFR field `plan/add/natural` for example

![image](https://user-images.githubusercontent.com/104912/132955450-be8acd38-b6ca-408e-920d-12612e1130b9.png)

**Comment by mstenta** [comment]
Ah now that I think about it, I believe this is actually related to https://github.com/mstenta/farm_nfa/issues/74

> indicate what to do to fix/add CFRs or add compartments

In the location widget, users will be selecting existing CFRs, and then existing compartments. But @LeScruf described cases where Compartments may not be created yet under certain CFRs, and so users may need to create them before they can record a log against them.

So this may end up just being `#description` text within the custom form/widget you are creating for #74 @pcambra 

Maybe when you have a first pass done at the UI for that you can paste a screenshot in #74 and I can work off of that?

I imagine it will be something as simple as "If the desired compartment does not yet exist in the system, a new record must be created for it. This can be done via the [Add Compartment](/asset/add/compartment) form."

**Comment by pcambra** [comment]
We need to discuss this as the PR above is not clear
