### ISSUE TITLE
Plans UI dashboard

### ISSUE THREAD

**Issue by pcambra** [mstenta/farm_nfa#91]
Mock dashboard
- Map of all CFRs within the plan
- Table of all tasks/activities
- Yield curve (placeholder)

**Comment by LeScruf** [comment]
[Natural Forest Plan - summary.pdf](https://github.com/mstenta/farm_nfa/files/7293951/Natural.Forest.Plan.-.summary.pdf)
[PlantationPlan - summary.pdf](https://github.com/mstenta/farm_nfa/files/7293954/PlantationPlan.-.summary.pdf)

**Comment by pcambra** [comment]
Add the popup behaviour for the map on plans
