### ISSUE TITLE
Update to farmOS 2.0.0-alpha3

### ISSUE THREAD

**Issue by mstenta** [mstenta/farm_nfa#94]
farmOS 2.0.0-alpha3 will be released soon, and includes some updates that we need/want in NFA.

I'm creating this as an issue just so we remember to factor in the update and deployment process (lots of potentially breaking changes will require us to do a fresh install and migration), and also so we can reference it from other issues.

**Comment by mstenta** [comment]
Just a reminder: we can update the migration instructions in this repo's README.md after alpha3, because we've resolved some of the migration rollback issues, and are going to introduce a simple `drush farm_migrate:import` command that runs all migrations in the correct order.

**Comment by mstenta** [comment]
farmOS is removing `config_rewrite`, so we will need to include it explicitly in this project.

**Comment by mstenta** [comment]
Another consideration we should think about: we're adding a `farm_update` module that will automatically revert overridden configuration on cache rebuilds. We can either disable this module in NFA, or we can use one of the options available for excluding certain items from automatic reverts.

**Comment by mstenta** [comment]
Opened a pull request: https://github.com/mstenta/farm_nfa/pull/104

> we're adding a `farm_update` module that will automatically revert overridden configuration

This did not get merged before tagging `2.0.0-alpha3` so we don't need to think about it (yet).

**Comment by pcambra** [comment]
We can close this one after updating to Alpha 4
